CREATE TABLE EMPLOYEES (
    EMP_ID VARCHAR(7) NOT NULL,
    EMP_NAME VARCHAR(30) NOT NULL,
	EMP_SALARY INT NOT NULL,
    MANAGER VARCHAR(3) NOT NULL,
    PRIMARY KEY (EMP_ID)
);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_SALARY, MANAGER)
			VALUES ('1234567', 'Amara Romanoff', 20.25, 'YES'); 
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_SALARY, MANAGER)
			VALUES ('2365478', 'Laney Zane', 23.25, 'YES'); 
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_SALARY, MANAGER)
			VALUES ('1511244', 'Chad Dylan', 13.25, 'NO'); 
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_SALARY, MANAGER)
			VALUES ('2334543', 'Sarah Flack', 13.25, 'NO'); 
            
CREATE TABLE CUSTOMERS(
	CUST_NAME VARCHAR(30) NOT NULL,
    CUST_ORDERNO VARCHAR(7) NOT NULL,
	CUST_AMNT INT NOT NULL,
	CUST_COST INT NOT NULL,
	CUST_EMAIL VARCHAR(50) NOT NULL,
	CUST_ADDRESS VARCHAR(50) NOT NULL
);

INSERT INTO CUSTOMERS (CUST_NAME, CUST_ORDERNO, CUST_AMNT, CUST_COST, CUST_EMAIL, CUST_ADDRESS)
			VALUES ('Ricky Remero', '2323234', 1, 200, 'remero@yahoo.com', '327 Journey St'); 
INSERT INTO CUSTOMERS (CUST_NAME, CUST_ORDERNO, CUST_AMNT, CUST_COST, CUST_EMAIL, CUST_ADDRESS)
			VALUES ('Remmy Peterson', '1287356', 2, 120, 'Gamit34@yahoo.com', '224 West Avenue'); 
INSERT INTO CUSTOMERS (CUST_NAME, CUST_ORDERNO, CUST_AMNT, CUST_COST, CUST_EMAIL, CUST_ADDRESS)
			VALUES ('Sydney Blanch', '5643176', 3, 180, 'SBlanch@hotmail.com', '3344 Blackwater Rd'); 
INSERT INTO CUSTOMERS (CUST_NAME, CUST_ORDERNO, CUST_AMNT, CUST_COST, CUST_EMAIL, CUST_ADDRESS)
			VALUES ('Avery Dawn', '2233445', 1, 25, 'NewDawn@gmaiil.com', '782 Cypres PT apt 709'); 
         
CREATE TABLE HARDWARE (
    HARDWARE_NAME VARCHAR(25) NOT NULL,
    HARDWARE_MAKE VARCHAR(25) NOT NULL,
	HARDWARE_ID VARCHAR(7) NOT NULL,
	HARDWARE_AMNT INT NOT NULL,
    HARDWARE_PRICE INT NOT NULL
);

INSERT INTO HARDWARE (HARDWARE_NAME, HARDWARE_MAKE, HARDWARE_ID, HARDWARE_AMNT, HARDWARE_PRICE)
			VALUES ('Xbox One', 'Microsoft', '1092367', 40, 250);
INSERT INTO HARDWARE (HARDWARE_NAME, HARDWARE_MAKE, HARDWARE_ID, HARDWARE_AMNT, HARDWARE_PRICE)
			VALUES ('Playstation 4', 'Sony', '2097865', 40, 250);
INSERT INTO HARDWARE (HARDWARE_NAME, HARDWARE_MAKE, HARDWARE_ID, HARDWARE_AMNT, HARDWARE_PRICE)
			VALUES ('Gaming PC', 'AMD', '1298754', 40, 1200);
INSERT INTO HARDWARE (HARDWARE_NAME, HARDWARE_MAKE, HARDWARE_ID, HARDWARE_AMNT, HARDWARE_PRICE)
			VALUES ('DVD Player', 'Panasonic', '4098321', 40, 150);
            
CREATE TABLE GAMES (
    GAME_TITLE VARCHAR(25) NOT NULL,
    GAME_PUBL VARCHAR(25) NOT NULL,
	GAME_ID VARCHAR(7) NOT NULL,
	GAME_PRICE INT NOT NULL,
    GAME_AMOUNT INT NOT NULL
);     

INSERT INTO GAMES (GAME_TITLE, GAME_PUBL, GAME_ID, GAME_PRICE, GAME_AMOUNT)
			VALUES ('Borderlands 3', '2K', '9876345', 100, 60);
INSERT INTO GAMES (GAME_TITLE, GAME_PUBL, GAME_ID, GAME_PRICE, GAME_AMOUNT)
			VALUES ('Halo Reach', 'Microsft', '9853216', 100, 60);
INSERT INTO GAMES (GAME_TITLE, GAME_PUBL, GAME_ID, GAME_PRICE, GAME_AMOUNT)
			VALUES ('Super Smash Bros.', 'Nintendo', '9654278', 100, 60);
INSERT INTO GAMES (GAME_TITLE, GAME_PUBL, GAME_ID, GAME_PRICE, GAME_AMOUNT)
			VALUES ('Devil May Cry V', 'Capcom', '9987656', 100, 60);

CREATE TABLE MOVIES (
    MOVIE_TITLE VARCHAR(50) NOT NULL,
    MOVIE_STUDIO VARCHAR(50) NOT NULL,
	MOVIE_ID VARCHAR(7) NOT NULL,
	MOVIE_PRICE INT NOT NULL,
    MOVIE_AMOUNT INT NOT NULL
);     

INSERT INTO MOVIES (MOVIE_TITLE, MOVIE_STUDIO, MOVIE_ID, MOVIE_PRICE, MOVIE_AMOUNT)
			VALUES ('Avengers: Infinity War', 'Disney', '4098765', 25, 100);
INSERT INTO MOVIES (MOVIE_TITLE, MOVIE_STUDIO, MOVIE_ID, MOVIE_PRICE, MOVIE_AMOUNT)
			VALUES ('Dispicable Me', 'Paramount', '4765421', 25, 100);
INSERT INTO MOVIES (MOVIE_TITLE, MOVIE_STUDIO, MOVIE_ID, MOVIE_PRICE, MOVIE_AMOUNT)
			VALUES ('Saw VI', 'Capstone', '4198342', 25, 100);
INSERT INTO MOVIES (MOVIE_TITLE, MOVIE_STUDIO, MOVIE_ID, MOVIE_PRICE, MOVIE_AMOUNT)
			VALUES ('Star Wars VII', 'Lucasfilm', '4124533', 25, 100);
            
CREATE TABLE CDS (
    CD_ARTIST VARCHAR(50) NOT NULL,
    CD_TITLE VARCHAR(50) NOT NULL,
	REC_COMP VARCHAR(50) NOT NULL,
	CD_ID VARCHAR(7) NOT NULL,
    CD_PRICE INT NOT NULL,
    CD_AMOUNT INT NOT NULL
);     

INSERT INTO CDS (CD_ARTIST, CD_TITLE, REC_COMP, CD_ID, CD_PRICE, CD_AMOUNT)
			VALUES ('Green Day', 'Revolution Radio', 'Fearless Records', '7665544', 10, 100);
INSERT INTO CDS (CD_ARTIST, CD_TITLE, REC_COMP, CD_ID, CD_PRICE, CD_AMOUNT)
			VALUES ('Fall Out Boy', 'Infinity on High', 'Warner Music', '7554421', 10, 100);
INSERT INTO CDS (CD_ARTIST, CD_TITLE, REC_COMP, CD_ID, CD_PRICE, CD_AMOUNT)
			VALUES ('All Time Low', 'Love Like War', 'Hopeless Records', '7998865', 10, 100);
INSERT INTO CDS (CD_ARTIST, CD_TITLE, REC_COMP, CD_ID, CD_PRICE, CD_AMOUNT)
			VALUES ('Crown the Empire', 'Rise of the Runaways', 'Fearless Records', '7112234', 10, 100);

CREATE TABLE INVENTORY (
    TOTAL_AMNT INT DEFAULT 0 NOT NULL,
	TOTHARDWARE_AMNT INT DEFAULT 0 NOT NULL,
	TOTCD_AMNT INT DEFAULT 0 NOT NULL,
    TOTGAMES_AMNT INT DEFAULT 0 NOT NULL,
    TOTMOVIES_AMNT INT DEFAULT 0 NOT NULL
);

#Stored Procedures# 
CREATE PROCEDURE SelectAllEmployees()
SELECT * FROM EMPLOYEES;

CALL SelectAllEmployees;

CREATE PROCEDURE SelectAllManagers()
SELECT * FROM EMPLOYEES
WHERE MANAGER = 'YES';

CALL SelectAllManagers();

CREATE PROCEDURE SelectAllHardware()
SELECT * FROM HARDWARE;

CALL SelectAllHardware();

CREATE PROCEDURE SelectAllGames()
SELECT * FROM GAMES;

CALL SelectAllGames();

CREATE PROCEDURE SelectAllMovies()
SELECT * FROM MOVIES;

CALL SelectAllMovies();

CREATE PROCEDURE SelectAllCDs()
SELECT * FROM CDS;

CALL SelectAllCDs();

CREATE PROCEDURE HardwareTotal()
INSERT INTO INVENTORY (TOTHARDWARE_AMNT)
SELECT SUM(HARDWARE_AMNT) FROM HARDWARE;

CALL HardwareTotal();
SELECT TOTHARDWARE_AMNT FROM INVENTORY;

CREATE PROCEDURE CDTotal()
INSERT INTO INVENTORY (TOTCD_AMNT)
SELECT SUM(CD_AMOUNT) FROM CDS;

CALL CDTotal();
SELECT TOTCD_AMNT FROM INVENTORY;

CREATE PROCEDURE GamesTotal()
INSERT INTO INVENTORY (TOTGAMES_AMNT)
SELECT SUM(GAME_AMOUNT) FROM GAMES;

CALL GamesTotal();
SELECT TOTGAMES_AMNT FROM INVENTORY;

CREATE PROCEDURE MoviesTotal()
INSERT INTO INVENTORY (TOTMOVIES_AMNT)
SELECT SUM(MOVIE_AMOUNT) FROM MOVIES;

CALL MoviesTotal();
SELECT TOTMOVIES_AMNT FROM INVENTORY;

CREATE PROCEDURE InventoryTotal()
SELECT SUM(TOTHARDWARE_AMNT * TOTCD_AMNT * TOTGAMES_AMNT * TOTMOVIES_AMNT) FROM INVENTORY
		AS TOTAL_AMNT;

CALL InventoryTotal();
